### ISSUE TITLE
Нельзя заимпортить es>5 библиотеку

### ISSUE THREAD

**Issue by stepancar** [alfa-laboratory/arui-scripts#103]
Desktop/projects/newclick-host-ui/node_modules/newclick-components/dist/index.js:1
export * from './components';
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:983:16)
    at Module._compile (internal/modules/cjs/loader.js:1033:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)
    at Module.load (internal/modules/cjs/loader.js:914:32)
    at Function.Module._load (internal/modules/cjs/loader.js:822:14)
    at Module.require (internal/modules/cjs/loader.js:956:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/stepancar/Desktop/projects/newclick-host-ui/node_modules/newclick-composite-components/dist/index.js:1:122)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1103:10)

Что с этим можно сделать?

**Comment by 7rulnik** [comment]
какие настройки  babel-preset-env?

**Comment by stepancar** [comment]
https://github.com/alfa-laboratory/arui-scripts/blob/master/configs/babel-client.js#L8
@7rulnik
