### ISSUE TITLE
Error: Cannot find module 'source-map-support'

### ISSUE THREAD

**Issue by Luchanso** [alfa-laboratory/arui-scripts#15]
В продакшен сборке, при запуске приложения возникает ошибка:
```
module.js:538
    throw err;
    ^

Error: Cannot find module 'source-map-support'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/src/.build/server.js:1:63)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

Разве source-map-support не является частью зависимости arui-scripts?

**Comment by Luchanso** [comment]
Проблема больше не воспроизводится, возможно был фикс...
