### ISSUE TITLE
Поломан запуск тестов

### ISSUE THREAD

**Issue by Luchanso** [alfa-laboratory/arui-scripts#90]
Очевидно, что регулярка для тестов захватывает также файлы снепшотов и файлы, которые к тестам имеют косвенное отношение

Лог тестов:
```jest
FAIL src/components/__tests__/__snapshots__/SignChooseSignTypeModal.test.jsx.snap
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at node_modules/arui-scripts/node_modules/jest-cli/build/TestScheduler.js:256:22
          at async Promise.all (index 11)

FAIL src/components/__tests__/__snapshots__/SignChooseCertificateModal.test.jsx.snap
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at node_modules/arui-scripts/node_modules/jest-cli/build/TestScheduler.js:256:22
          at async Promise.all (index 12)

FAIL src/components/__tests__/__snapshots__/SignErrorsModal.test.jsx.snap
  ● Test suite failed to run

    Your test suite must contain at least one test.

      at node_modules/arui-scripts/node_modules/jest-cli/build/TestScheduler.js:256:22
          at async Promise.all (index 13)
```
Лог дебага:
```log
yarn run v1.22.0
$ arui-scripts test --debug
{
  "configs": [
    {
      "automock": false,
      "browser": false,
      "cache": true,
      "cacheDirectory": "/var/folders/4d/9_hg7b2n7cl__t_70q7v6jdc0000gn/T/jest_dx",
      "clearMocks": false,
      "coveragePathIgnorePatterns": [
        "/node_modules/"
      ],
      "detectLeaks": false,
      "detectOpenHandles": false,
      "errorOnDeprecated": false,
      "filter": null,
      "forceCoverageMatch": [],
      "globals": {
        "ts-jest": {
          "tsConfig": "/Users/luchanso/dev/alfa/blabla/tsconfig.json"
        }
      },
      "haste": {
        "providesModuleNodeModules": []
      },
      "moduleDirectories": [
        "node_modules"
      ],
      "moduleFileExtensions": [
        "ts",
        "tsx",
        "js",
        "jsx"
      ],
      "moduleNameMapper": [
        [
          "\\.css$",
          "/Users/luchanso/dev/alfa/blabla/node_modules/arui-scripts/configs/jest/css-mock.js"
        ]
      ],
      "modulePathIgnorePatterns": [],
      "name": "2f7b09c41a1cfd09ff9b37ae6c59e012",
      "prettierPath": null,
      "resetMocks": false,
      "resetModules": false,
      "resolver": null,
      "restoreMocks": false,
      "rootDir": "/Users/luchanso/dev/alfa/blabla",
      "roots": [
        "/Users/luchanso/dev/alfa/blabla"
      ],
      "runner": "jest-runner",
      "setupFiles": [
        "/Users/luchanso/dev/alfa/blabla/node_modules/arui-scripts/configs/jest/setup.js"
      ],
      "setupTestFrameworkScriptFile": null,
      "skipFilter": false,
      "snapshotSerializers": [
        "/Users/luchanso/dev/alfa/blabla/node_modules/jest-snapshot-serializer-class-name-to-string/index.js"
      ],
      "testEnvironment": "jest-environment-jsdom",
      "testEnvironmentOptions": {},
      "testLocationInResults": false,
      "testMatch": [],
      "testPathIgnorePatterns": [
        "/node_modules/"
      ],
      "testRegex": "(^.*src).*(((/__test__/|/__tests__/).*)|(test|spec|tests)).(jsx?|tsx?$)",
      "testRunner": "/Users/luchanso/dev/alfa/blabla/node_modules/jest-jasmine2/build/index.js",
      "testURL": "http://localhost",
      "timers": "real",
      "transform": [
        [
          "^.+\\.jsx?$",
          "/Users/luchanso/dev/alfa/blabla/node_modules/arui-scripts/configs/jest/babel-transform.js"
        ],
        [
          "^.+\\.tsx?$",
          "/Users/luchanso/dev/alfa/blabla/node_modules/arui-scripts/node_modules/ts-jest/dist/index.js"
        ],
        [
          "^(?!.*\\.(js|jsx|ts|tsx|css|json)$)",
          "/Users/luchanso/dev/alfa/blabla/node_modules/arui-scripts/configs/jest/file-transform.js"
        ]
      ],
      "transformIgnorePatterns": [
        "/node_modules/"
      ],
      "watchPathIgnorePatterns": []
    }
  ],
  "globalConfig": {
    "bail": false,
    "changedFilesWithAncestor": false,
    "collectCoverage": false,
    "collectCoverageFrom": [
      "src/**/*.{js,jsx,ts,tsx}"
    ],
    "coverageDirectory": "/Users/luchanso/dev/alfa/blabla/coverage",
    "coverageReporters": [
      "json",
      "text",
      "lcov",
      "clover"
    ],
    "coverageThreshold": null,
    "detectLeaks": false,
    "detectOpenHandles": false,
    "errorOnDeprecated": false,
    "expand": false,
    "filter": null,
    "globalSetup": null,
    "globalTeardown": null,
    "listTests": false,
    "maxWorkers": 7,
    "noStackTrace": false,
    "nonFlagArgs": [],
    "notify": false,
    "notifyMode": "always",
    "passWithNoTests": false,
    "projects": null,
    "rootDir": "/Users/luchanso/dev/alfa/blabla",
    "runTestsByPath": false,
    "skipFilter": false,
    "testFailureExitCode": 1,
    "testPathPattern": "",
    "testResultsProcessor": null,
    "updateSnapshot": "new",
    "useStderr": false,
    "verbose": null,
    "watch": false,
    "watchman": true
  },
  "version": "23.6.0"
}
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by Luchanso** [comment]
Стало воспроизводится после 8.2.3 версии https://github.com/alfa-laboratory/arui-scripts/pull/79/commits/8a8729bad9fc9ebf3897e96dc00a95bf3f8b7ee7

До этого работает
